### ISSUE TITLE
Add tables of zero-order correlations for each mixed-effects analysis to supplemental materials

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#10]
"There are also many predictors used in the mixed effects analyses (Tables 2-6). It is hard to know whether these analyses are adequately powered (what citations support the use of 20 observations per cell?), and whether predictors are colinear (as no zero-order correlations are provided)."

**Comment by angelinetsui** [comment]
For citation of the use of 20 observation per cell (Simmon et al., 2011, Psych Sci)

For collinearity check, I will take a look and work on it later in 06.Rmd. Unsure if we need to report zero-order correlations. What is the use of zero-order correlations between all the IVs and DV, if we can show that we don't violate the multicollinearity assumption?

**Comment by kristabh** [comment]
Since the reviewer asks, I think it's no problem to report the zero-order correlations in the supplementals.  Besides multicollinearity, they might just be curious.

**Comment by angelinetsui** [comment]
happy to do it later, but I will appreciate help from others in the analysis team to work on the zero-order correlations table while I am working on the residuals analysis and linear model assumption checks

**Comment by angelinetsui** [comment]
Hi Krista, I checked the multicollinearity assumption for each lme4 model. The first three models did not violate this assumption as no IV has VIF > 10. However, the two SES models violated this assumption and it looked like that we might need to remove a number of variables (e.g., trial_type, age and SES*trial_type).......I didn't push yet because I am still waiting for a statistician's advice for treating age as dummy or not. The way that we center age/treat age as dummy will affect VIF, so I will push once I have an answer and reach consensus with you first.

Another thing is whether we really need to create zero-order correlations in the supplementals. Note that we have two datasets, yielding 5 different mixed-effect models. We have A LOT of variables in each model. Also, does the reviewer expect correlation between interactions as well? Well, we have A LOT OF interactions in each model, so if the reviewer asked this question because of multicollinearity issues, we will need to report correlations between interaction terms and intercept as well. So just an example for LMM1 in our paper will generate a 19*19 Matrix....This is a very large matrix and I doubt people will read it. Indeed, we can use one line of codes (lme4) to generate this kind of table in OSF (i.e., the mixed-effect model can generate the correlation table). We can simply refer readers to the OSF link instead of creating multiple tables in the supplemental materials. What do you think?

**Comment by kristabh** [comment]
I don't think it's reasonable to remove trial_type or SES*trial_type in our model because this pertains to our main research question. So we either need to keep as-is, remove something else, or omit the SES models entirely.

For zero-order correlations, I think it's reasonable to just report the correlations between the main effects, and not the interactions - perhaps one table for the lab-matched, and one table for the full dataset. As you say, readers can compute correlations for themselves if they want more.

**Comment by angelinetsui** [comment]
I will try removing something else and see if this will solve the multicollinearity issue. And I agree that SES*trial_type is a key question. 

For zero-order correlation table, I can do it for main effects.

**Comment by angelinetsui** [comment]
Hi Krista, we still have the problem of multicollinearity for SES model. 

For the SES matched dataset, the following variables have very high VIF (multicollinearity index):

- trial_type 
- age_mo_c 
- trial_type:age_mo_c 
- trial_type:SES 
- age_mo_c:SES 
- trial_type:age_mo_c:SES 

For the SES unmatched dataset, the following variables have very high VIF (multicollinearity index):

- age_mo_c 
- trial_type:age_mo_c 
- age_mo_c:SES 
- trial_type:age_mo_c:SES 

I think that we need to remove some variables and re-run the model and see if this can solve the multicollinearity problem. I don't think that we can remove trial type, this is our primary research question. But age_mo_c may be a potential candidate. What do you think?

**Comment by kristabh** [comment]
I would start by removing the three-way interaction trial_type:age_mo_c:SES, and if that does not help, then removing age_mo_c:SES as well.  I don't think either of these are particularly interesting to us.

**Comment by angelinetsui** [comment]
Thanks Krista, you are right, we really need to remove the three-way interaction trial_type:age_mo_c:SES in both SES models to remove the "multicollinearity issues". Currently, I cannot enter "trial_type:SES" into the SES-lab-matched dataset, but I can enter this two-way interaction into the SES-full_dataset. In sum, SES has no effect on the IDS.

We will need to change our discussion a bit by removing our interpretation about SES effect on IDS and age. 

Does it make sense to you? I want to confirm with you before pushing any changes. Many thanks!

**Comment by kristabh** [comment]
Just to clarify, when you say you cannot enter "trial_type:SES" do you mean because of multicollinearity or because the model does not converge or some other reason?

I agree that we will def. need to remove the three-way interaction, and change the discussion as necessary.

**Comment by angelinetsui** [comment]
Hi Krista, thank you for your question. In this issue, we do not have the problem of centering. And I also don't find how different centering will reduce the problem of multicollinearity. 

Based on the model now, we have a problem of multicollinearity. The model has converged but we are not statistically justified to simply report that because we violate multicollinearity. Sorry that I missed this assumption checking in earlier RR (we actually did not check any multicollinearity in MB1..... I think we failed to see how variables in the model may have high correlations..). Anyway, because we violated the multicollinearity assumption in the two SES models, we must remove some variables that has extremely high VIF (an index for multicollinearity) from the model.

We have two datasets: full dataset has a bigger sample size than lab-matched dataset, so we will need to remove more variables from lab-matched dataset.

My investigation suggested the following:

1) For the SES lab-matched model, the interaction terms: "trial_type:SES" and "trial_type:age_mo_c:SES" are reported to be the problematic and violate the multicollinearity assumption. So we really need to remove these two interactions from the model

2) For the SES full model, after removing "trial_type:age_mo_c:SES", we will solve the problem of multicollinearity

I hope that this is clear now. Please let me know if you have any questions

**Comment by kristabh** [comment]
Okay, please go ahead and do that (i.e., remove those problematic interactions), and update the text in the manuscript...

**Comment by angelinetsui** [comment]
I am working on the zero-order correlation table here. Got a bit of problem here as most of our variables in the lmer models are categorical (except for two variables: age and trial_num). We literally cannot compute a zero-order correlation (i.e. zero-order correlation implies "Pearson correlation" not spearman rank correlation) table here......What should we do?

**Comment by kristabh** [comment]
If you compute Pearson's R between binary and continuous, won't you get a point-biserial correlation? And for two categorical, won't you get phi?  I think these details of interpretation will be in the figure legend.

http://web.pdx.edu/~newsomj/pa551/lectur15.htm

**Comment by angelinetsui** [comment]
I can't compute a Pearson correlation between categorical variables in R (but if I am wrong, please correct me. Well, just realized that we can force it by changing the variable to dummy-coded, I guess, but I am worried about interpretation). I wonder if we need to compute correlation using different metrics here. For two continuous variables, use Pearson. For one continuous variable and one dichotomous variable, use Point-biserial Correlation. For two dichotomous variables, use Phi. For categorical variables that are not dichotomous, use Cramer's V? This makes the whole thing quite complicated though!

**Comment by angelinetsui** [comment]
Hi Krista, after pondering this issue, I need to seek your advice what to report in the table. In our mixed-effect models, our DV is always log-transformed looking time. So if we want to report the main effects only, perhaps we can report only the correlations between DV and all the main effects (e.g., age, trial_type, lang_group, trial_num and etc) in the model. As the DV is always continuous, we are either reporting Pearson correlation or point-biserial correlations in the table.

I suggest not reporting correlations between IVs (e.g., age and trial_num), readers can always refer back to our Github codes for the multicollinearity check if they want to know how the IVs correlated with each other and wonder if we violate the assumption. This will avoid the problems of making a lot of tables and reporting different correlation metrics (e.g., two categorical variables will need phi, and some of them need cramer's v, all depending on the nature of the variables)? What do you think?

**Comment by kristabh** [comment]
Okay, re-reading the reviewer's comment, I don't think it's necessary to provide these correlation tables - they wanted to know whether we had issues with multicolinearity.  I think we can deal with this comment simply by mentioning how you looked at VIF.  I tagged you in a comment in the manuscript.  I will close this issue.
