### ISSUE TITLE
Add standard math equations to describe models (perhaps in additional to R syntax in main text?)

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#12]
"I will say, however, that the manuscript is long and difficult to understand due to frequent references to the ManyBabies 1 manuscript and reliance on R code for the writing of models (with code differing across models); this paper does not stand alone. R code could certainly be used in the Appendix or Supplemental files, but reliance on it in the main text limits generalizability and will make the article inaccessible to some readers; it also hides the large number of predictors used in some models and seems to have prevented the specification of key model parameters (e.g., the covariance structure used for the error in mixed models)."

**Comment by angelinetsui** [comment]
@kristabh , I am trying to translate the lme4 R script to math equations. I found that even the math equation for the most simplest model (i.e., one of our pruned model) is complicated and long (i.e., we have a lot of interaction terms, main effects and different variances). And I have troubles in translating every "unpruned" model to the math equations, esp when a number of interactions are at least two-way or even three-way, and these interactions do not coexist across different group levels. For example, age*bilingual doesn't exist on the level of subid. I wonder if this is **NECESSARY** to translate everything into math equation in order to address ONE reviewers' concern. To be honest, I think that many people may understand the R codes more than math equation. In particular, the use of R codes to illustrate models appears not to be a big concern in RR stage 1 and Mb1, why do we need to do so? I think that it will take up quite a bit of time from me and I do need another person who is very good at HLM to look at the equation and translate some equations for me.

I am tagging Mike here to hear what he thinks too @mcfrank

**Comment by mcfrank** [comment]
I agree, honestly. I find the R formula notation to be simpler to read and
reason about, though it is true that it's less general than the formulae...
I would consider pushing back on this one.

**Comment by kristabh** [comment]
I also prefer the R formula notation.  I think we can make an argument that this is a stylistic matter.  Angeline, maybe you could check in the last issue or two of AMMPS and do a quick tally of papers that use each type of notation.  This would be evidence that both are used in AMMPS, so it's just a stylistic disagreement with the reviewer.  We can also mention that it's better for comparability with the MB1 manuscript.

**Comment by angelinetsui** [comment]
I will check the last two to three issues of AMMPS and see if anyone used math notation. Will get back to you later.

**Comment by angelinetsui** [comment]
I checked the last three issues in AMMPS. Results are somewhat mixed. Two papers used mixed level models didn't even include the lme 4 R equation and simply report how they control for random effects and fixed effects in text (which we have already done in the RR). One paper used mixed level model report the traditional math notation, but I note that this paper's model is MUCH MORE simpler than our models, because we have SO MANY interactions in the models. 

Any thoughts? @kristabh

**Comment by kristabh** [comment]
Okay, I have added some argument in the response letter to keep as-is.

**Comment by angelinetsui** [comment]
Thanks, looked good, let us see how other Mb1b collaborators think as well.
