### ISSUE TITLE
Check preprocessing / exclusion of monolinguals

### ISSUE THREAD

**Issue by christinabergmann** [manybabies/mb1b-analysis-public#22]
Are the data from the monolinguals properly preprocessed (i.e. the same way as in MB1, with exclusions of looking times shorter than 2s etc)?

**Comment by christinabergmann** [comment]
There are 4080 NA entries in the monolingual data from MB1.

**Comment by christinabergmann** [comment]
@angelinetsui @kristabh So after some digging the file `03_data_trial_main.csv` being read in is *not* the latest or previous version, but must be some much earlier version.
This is the link to the raw datafile as it is shared now: https://raw.githubusercontent.com/manybabies/mb1-analysis-public/master/processed_data/03_data_trial_main.csv (will always link to the latest version)

For comparison, this is what is being read in in `04_merge_with_monolinguals.Rmd`
https://raw.githubusercontent.com/manybabies/mb1-analysis-public/83358f804335452fe50e3eaf2831575635943ec9/processed_data/03_data_trial_main.csv

I suspect this older version was chosen because it contained info about the parents, SES, and so forth, but I am convinced it would be much better to use the file that is current and add this information through merging data. This requires some additional checking and code rewriting, so before getting started, I wanted your approval to go ahead. Mergingn with `03_data_diff_main.csv` should by the way yield the desired information.

**Comment by kristabh** [comment]
Thank you for your digging into this- this issue is important.  I don't remember the specific chronology of this particular ManyBabies file, but in any case I agree that it will be best to use the most recent version, and to archive this version on the MB1B repo. It you could work on this @christinabergmann , that would be amazing!

**Comment by angelinetsui** [comment]
Thanks so much for your help, @christinabergmann , totally agree with you with the use of current version. Thanks again for your work here :-)

**Comment by christinabergmann** [comment]
OK, quick update: I am on it but struggle to verify that the monolingual data are correct by replicating the stats from the paper. Holding off on a PR until this is sorted.

**Comment by kristabh** [comment]
Okay, thanks Christina!  I think once this is sorted we will be on the home stretch!

**Comment by christinabergmann** [comment]
OK, I fixed the bit about the reading in of the correct datafile (my validation didn't take into account the age subsetting). NA looking times however occur both in the bilingual as well as the monolingual dataset, so it needs to be fixed programmatically elsewhere.
In MB1, this is how it's handled:

`d_lmer <- d %>%
  filter(trial_type != "train") %>%
  mutate(log_lt = log(looking_time),
         age_mo = scale(age_mo, scale = FALSE),
         trial_num = trial_num, 
         item = paste0(stimulus_num, trial_type)) %>%
  filter(!is.na(log_lt), !is.infinite(log_lt))`

**Comment by kristabh** [comment]
I think we will need to integrate this into the exclusions script for the bilinguals, and just make sure that the correct n's for monolinguals are represented elsewhere (since we are not reporting those exclusions).  @angelinetsui is this something you can tackle?

**Comment by angelinetsui** [comment]
Sorry for the late reply. To all, I don't think the problem has solved. I did pull the new changes Christina made, but the same problem exists. In the lmer model, all the additional excluded infants with NA looking time were still monolinguals. This is bizarre, because monolingual infants who did not contribute at least 2 trials should be excluded before entering the data frame for lmer data analysis. Please go to 05.Rmd and see my codes starting from LMM model 1: Matched and LMM model 1: Unmatched. I have used set.diff to find out who contributed NA looking time.

As for the !is.na(log_lt), I always have these codes in 05.Rmd and Paper.Rmd, so all the analyses reported in the mb1b are the same as we had removed any NA looking time trials before analyses. The problem is related to the mismatch between the number of monolingual infants included in the paper and the number of monolingual infants entered the lmer model because any monolingual infants excluded contributed NA looking time.

**Comment by jkosie** [comment]
I can take a peek at this too if it would be helpful (though happy not to if it would be too many people working on the same issue). I had mentioned previously that I thought the number of monolingual infants for Baby Lab Princeton looked weird, and maybe it's related to this issue.

**Comment by angelinetsui** [comment]
@jkosie @christinabergmann , it will be great if either of you can look into this issue further. I have included my codes (checking which lab has infants who contributed NA looking time and were removed from the lmer codes (!is.na(log_lt)). I don't see any infants from Baby Lab Princeton in this subgroup, but please correct me if I am wrong. Thanks very much for your help!!

**Comment by christinabergmann** [comment]
OK, I've proposed two changes, one in the exclusions script for bilinguals when also removing short LT, this seemed the appropriate place, and in the merge with monolinguals script when reading in the monolingual data. 

Good catch, everyone, I think now the numbers should be correct (I am traveling, so please triple check my added lines)

**Comment by angelinetsui** [comment]
all good now, thanks @christinabergmann .  For removing short LT, we actually had a code chunk in the 03_exclusion.Rmd from line 37 to 44

d$short_lt <- d$looking_time < 2

short_lt <- exclude_by(d, quo(short_lt), action = "NA out", 
                   return_pcts = TRUE, 
                   quiet = TRUE)
d <- short_lt$data

So I think we are good

**Comment by christinabergmann** [comment]
Good.
I was actually wondering about that chunk, it's duplicate with exclusions.Rmd, isn't it?

**Comment by angelinetsui** [comment]
For NA looking time codes, it is not duplicated, but if we have codes for removing LT > 2, yes
