### ISSUE TITLE
Clarification - missing trials in meta-analysis

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#46]
I'm trying to understand why the number of missing trials reported is not twice the number of missing trial pairs here.  Does this section need to be re-written?

"To estimate an effect size for each data set, we first computed individual infants’ preference for IDS over ADS by (a) subtracting looking time to the ADS stimulus from looking time to the IDS stimulus within each yoked trial pair and (b) then computing a mean difference score for each infant. Pairs that had a trial with missing data were excluded (34.53% of pairs in the lab-matched data set, 25.41% of pairs in the full data set), which constituted a total of 20.58% of trials in the lab-matched data set and 13.78% of trials in the full data set"

**Comment by angelinetsui** [comment]
Our R script for calculating the missing pair trials (matched dataset) are as follow: 

percent_pairs_missing_matched <- round(((sum(is.na(d_diffs_matched$diff))/length(d_diffs_matched$diff))*100), 2)

percent_trials_missing_matched <- round(((sum(is.na(d_diffs_matched$IDS), is.na(d_diffs_matched$ADS))/(2*length(d_diffs_matched$diff)))*100), 2)

For pairs that only have 1 trial missing, this will count as 1 in pair_missing and 0.5 in trial missing (i.e., we divide it into halve). So this may be the reason why there is difference. But I am also trying to understand why the trials % is > 50% of the trial pair, as 0.5 should make the number of trials missing smaller. Any thoughts, @kristabh

**Comment by kristabh** [comment]
Yes, this is exactly the question and what I need you to figure out.  I will tag @jkosie in case she may be able to help.

**Comment by jkosie** [comment]
I just tried to work this out for the lab-matched dataset. Sorry if this seems pedantic, I'm just trying to work it all out in my head!

There are 1030 trial pairs missing. Out of 2983 possible pairs, this is 34.53% of pairs that are missing.

If _both_ trials were missing in each of those pairs, there would be 2060 trials missing. Because there are 2983 pairs, there are 5966 trials. 2060 would be 34.53% of trials. This makes sense that we would expect it to be the _same_ percentage, because we're doubling everything. 

However, just because a pair is missing doesn't mean that there are two trials missing. Of the missing pairs, 440 have missing ADS, 392 have missing IDS, and 198 have both missing. That's a total of 440 + 392 + (198*2) = 1228 missing trials. Out of the 5966 trials (2983 pairs * 2), this is 20.58%. 

So, it seems like the numbers in the paper are correct. Basically, I think the confusing thing here is that the denominator is getting doubled as well when calculating the percent of trials missing. Is there something else I'm missing?

**Comment by angelinetsui** [comment]
Thanks very much, Jessica! What you said make senses.

**Comment by kristabh** [comment]
Got it.  I think the previous wording was confusing.  I re-wrote as:

"A total of 20.58% of trials in the lab-matched data set and 13.78% of trials in the full data set were missing. Trial pairs that that had either one or both trials missing were excluded from the analysis, which constituted 34.53% of pairs in the lab-matched data set and 25.41% of pairs in the full data set."
