### ISSUE TITLE
LMEM tables

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#50]
In the manuscript, LMEM tables don't always print out to three significant digits.  Is it just because of trailing zeros?  Looking at the output tables before they are printed by apa_table, it doesn't seem like it should always round this way.

**Comment by jkosie** [comment]
I've figured this out, but I need to play around a little more to get the right fix.

This is happening because the numbers in the table are characters and not numbers, so they're not rounding. I tried a quick fix of just changing the values using `as.numeric()` That works for the rounding issue (they all go to 3 digits), but then the p-values sometimes become 0.00, which I don't think we want. I'll see if there's a better way.

**Comment by kristabh** [comment]
I need to update everything manually in a word document anyway (cut and paste - the copy editor has already been through), so don't worry about the p-values.  Do you just want to send me the correctly rounded table?

**Comment by jkosie** [comment]
The numbers is the table are different when I knit to word versus knit to pdf. I know we had this issue before (issue #45). Is there one we decided was the correct version to stick with?

**Comment by kristabh** [comment]
Thanks for fixing this Jess.  Just as a note we used rounded versions from the .pdf in the final manuscript.
