### ISSUE TITLE
Reorder data in Figure 1

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#6]
p. 32, Figure 1. What does it mean that “points are scaled by inverse variance”? Ditto comment from Table 1 about ordering and labeling."

Our response:
We have now re-ordered Figure 1 according to the effect size of the monolingual-bilingual difference.  We thank the reviewer for this suggestion.

Make sure to change figure caption.

**Comment by jkosie** [comment]
I can take this one too. I searched for it in particular because I was re-reading the paper and noticed that the table says that babylabprinceton collected data from only 1 monolingual 6-9 month old infant. I don't think that's correct (I think in mb1 they had ~20 monolinguals). Shouldn't these monolingual infants be included in that table or is there something I'm missing?

**Comment by kristabh** [comment]
Could their monolinguals be in an age bin that wasn't collected for MB1B?

**Comment by jkosie** [comment]
I looked at the mb1 data, and the infants were 6-9 months. I'll dig into the issue, I just thought I'd check first in case there was an obvious answer I was overlooking.

**Comment by jkosie** [comment]
@kristabh - your comment above says: "We have now re-ordered Figure 1 according to the effect size of the monolingual-bilingual difference. We thank the reviewer for this suggestion."

I don't see an effect size of the difference. Do you mean we should calculate the difference in effect size (e.g., monolingual - bilingual) and sort by that?

**Comment by kristabh** [comment]
Yeah, my suggestion was to calculate monolingual-bilingual and sort by that, but I'm open to other suggestions.  We might want to add that difference to the plot, together with the raw effect sizes for each group/lab.

**Comment by jkosie** [comment]
Got it! 

I think it makes sense to sort by that. I can add that difference to the plot as well so that we can decide if we want to keep it.

**Comment by jkosie** [comment]
I've updated the figure so that it's sorted by the difference between the monolingual and bilingual effect. 

It wasn't as straight-forward as I thought it would be, and I'm having trouble with the meta-analytic estimate facet getting squished. I'll keep trying to edit, but maybe someone else can take a look, too? (@christinabergmann - do you have ideas about how to fix it?)

I'm attaching an image where I've added the difference in effect size as a black X on the plot, but I think it might be confusing? Let me know if you'd like me to add it, though.

![Screen Shot 2020-06-08 at 3 53 57 PM](https://user-images.githubusercontent.com/7671648/84074335-6a35e580-a9a0-11ea-92ea-7f01c915ee20.png)

**Comment by kristabh** [comment]
I really like the black X as the difference.  Can you add it to the legend?  That might help to make it clear.

**Comment by jkosie** [comment]
Sure - I updated the code to include the X and edited the figure caption. I wasn't sure if we should remove the mention of inverse variance or add an explanation. It's still there for now.

**Comment by christinabergmann** [comment]
I think the figure looks great, thanks Jessica! Re: Inverse variance, phew, I don't know how else to frame it either. It's like asking to use a different word for median, imo. Maybe "points are scaled by precision, as indicated by the inverse of their variance"?

**Comment by kristabh** [comment]
Perfect.  I've added a similar wording to the text to explain inverse variance.  I think this issue can be closed.
